# Generated by Django 3.2.6 on 2021-08-12 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('phone', models.CharField(max_length=11)),
                ('address', models.TextField()),
            ],
            options={
                'db_table': 'dealer',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vin', models.CharField(max_length=17)),
                ('make', models.TextField()),
                ('model', models.TextField()),
                ('year', models.IntegerField()),
                ('dealer', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='car_sale_app.dealer')),
            ],
            options={
                'db_table': 'car',
            },
        ),
    ]
